export const VALIDATION_FAILED = 'VALIDATION_FAILED';
export const EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED';
export const TOKEN_NOT_PROVIDER = 'TOKEN_NOT_PROVIDER';
export const TOKEN_IS_INVALID = 'TOKEN_IS_INVALID';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const PASSWORD_DOES_NOT_MATCH = 'PASSWORD_DOES_NOT_MATCH';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
